### ISSUE TITLE
That support AMD/AMD ?

### ISSUE THREAD

**Issue by liberodark** [tux-n-vape/prime-switcher#1]
Hi,

My question is on new configuration of pc portable have config with VEGA GPU / RX 560X and use same driver amdpgu / amdgpu with modesetting.
Your software support this configuration ?

Best Regards

**Comment by wascardev** [comment]
Hello,

prime-switcher supports AMD-AMD configurations but in contrast to Intel-NVIDIA the discrete GPU is not power off when you are in performance mode (bbswitch doesn't support AMD).
