### ISSUE TITLE
Lightdm performance mode

### ISSUE THREAD

**Issue by Mario156090** [tux-n-vape/prime-switcher#2]
Hi, i am using this great tool, but i have the problem with lightdm. When i set up to performance mode i get a black screen, i whatched the fix of this and applied but i have not a good result. :(

Can you help me please?

I attached a picture of the update. Thank's.

![image](https://user-images.githubusercontent.com/47507975/61581520-d8ff1b80-ab0e-11e9-9579-4deae78c1152.png)

**Comment by wascardev** [comment]
Hi
I need more informations to solve the issue. What is your distro and PC specifications ?

**Comment by Mario156090** [comment]
Hi, my Distro is ArchLinux. My laptop is a Dell Inspiron 15000 7567
Core I5 7300HQ
Intel HD 630
NVIDIA 1050m
RAM 8G

If you need more information, please say me. Thank's

**Comment by wascardev** [comment]
Can you give me the result of command `lspci` ?

**Comment by Mario156090** [comment]
> Can you give me the result of command `lspci` ?

Yes, I can. Here:

[lspci.txt](https://github.com/tux-n-vape/prime-switcher/files/3414105/lspci.txt)

**Comment by Mario156090** [comment]
Hi @wascardev, Can you fix it?
If you need more information tell me. :)

**Comment by wascardev** [comment]
Try to set target driver on `nvidia` 

```bash
sudo prime-switcher -d nvidia -s performance
```

**Comment by Mario156090** [comment]
> Try to set target driver on `nvidia`
> 
> ```shell
> sudo prime-switcher -d nvidia -s performance
> ```

Hi, I tried this, none solution yet. :(

**Comment by Mario156090** [comment]
> Try to set target driver on `nvidia`
> 
> ```shell
> sudo prime-switcher -d nvidia -s performance
> ```

Dear dev, the problem is also with SDDM. :(

**Comment by wascardev** [comment]
I fixed some problem with SDDM in this commit https://github.com/tux-n-vape/prime-switcher/commit/8e2c256c9f7e223a3a1fd307a3f27656ff4cbf37

Try again
