### ISSUE TITLE
prime-switcher does not work via manjaro

### ISSUE THREAD

**Issue by sissisi** [tux-n-vape/prime-switcher#4]
Hi,

I have tested prime-switcher on manjaro, gnome and xfce are installed, with:
1) integrated graphic card: Intel 620
2)Discrete graphic card: nvidia gtx1050 mobile

I use an ASUS VivoBook Pro 17 N705UD.

I have a black screen on boot.

I suppose I must uninstall bumblebee, but your explanation is not clear about the installation of proprietary drivers.
Or I must follow the link: https://forum.manjaro.org/t/howto-set-up-prime-with-nvidia-proprietary-driver/40225
thanks.
edit:
I have installed:
1)gdm-prime :https://aur.archlinux.org/packages/gdm-prime
2)libgdm-prime: https://aur.archlinux.org/packages/libgdm-prime

I have not black-screen and have a GUI, but prime-switcher does not work completely.
I can only switch with the integrated card intel, but impossible to switch with discrete card.
even if I use this command:
[code]prime-switcher -d nvidia -s performance[/code]
(bumblebee is disabled)

**Comment by wascardev** [comment]
Bumblebee is not required and i recommand to don't install it. Only, one of its components is required, the kernel module bbswitch. I think gdm-prime and libgdm-prime is not compatible with prime-switcher because it patch gdm too.
